### PR TITLE
Add Elixir syntax highlighting

### PR DESCRIPTION
**Pull request by avli**

### CODE REVIEW

**Comment by avli** [comment]
The example of the highlighting is on the screenshot below.

screen shot 2015-01-08 at 18 03 33

**Comment by cmur2** [comment]
Cool! I personally don't use Exlixir (yet) but I'm happy to merge this :)

Would you mind putting your file under the GPLv2 license as the rest of the JOE source code so it could theoretically be bundled with it some day if one wants so? I'll merge regardless of your decision since this is very nice but I'd be happy if you think about it.

**Comment by utoddl** [comment]
On 01/08/2015 09:45 AM, Christian Nicolai wrote:
>
> Cool! I personally don't use Exlixir (yet) but I'm happy to merge this :)
>
> Would you mind putting your file under the GPLv2 license as the rest of
> the JOE source code so it could theoretically be bundled with it some
> day if one wants so? I'll merge regardless of your decision since this
> is very nice but I'd be happy if you think about it.
>
I would also like to point out that JOE is not the only editor which uses
JOE's syntax engine and .jsf files. At least one other, ne
(http://ne.di.unimi.it/) uses the same engine, and by having GPL'd .jsf
files we're able to include those with ne.

As such, I want to thank all those involved with the joe-syntax effort. It
goes beyond just JOE.
--
Todd

**Comment by avli** [comment]
@cmur2 I don't mind putting this code under the GPLv2, but not sure whether it is possible, because of I borrowed a few pieces of code from erlang.jsf and python.jsf. What do you think? 

I'm new to Elixir (but admire this language), so I hope to improve some aspects of this JSF in the future.

**Comment by cmur2** [comment]
@avil since python.jsf is originally from JOE it's under GPLv2 already and since I created erlang.jsf and submitted it to GPLv2 as well [here](https://github.com/cmur2/joe-syntax#licensing), there should be no problem regardless how big the chunks or ideas were that you borrowed. I've no problem with this, since those are meant for learning too.

Maybe you can add a short sentence to the pull request and/or a short notice in the file about GPLv2.

And @utoddl is absolutely right!

**Comment by avli** [comment]
@cmur2 Sounds good then. I don't mind if elixir.jsf will be licensed under GPLv2. I think, you can add a note about it in README.md as you already did for some syntax files. So, yes, it's under the GPLv2.

**Comment by cmur2** [comment]
Hey, sorry to bother you again with this licensing stuff - recent discussions with the original project showed that it would be nice to have a "GPL v2 or any later version" license statement to be prepared for future developments. I already updated this for myself in the README and wanted to ask kindly if you are willing to declare your contents as "GPL v2 or any later version"?

**Comment by avli** [comment]
Sure. Any content pulled by me to this repository as well as in my fork of this repository is GPL v2 or any later version.

**Pull request merged**
