### PR TITLE
A new strict JSON highlighter

### PR DESCRIPTION
**Pull request by iarna**
So previously we were just using the js highlighter for json, but that's not actually desirable as json doesn't accept lots of stuff that js does.  So I wrote this new json highlighter from scratch based on json.org– this should be complete to the point of highlighting any invalid JSON.

### CODE REVIEW

**Comment by cmur2** [comment]
Hi, I'm currently in the process of trying to get all the contributions to the original JOE project (http://sourceforge.net/projects/joe-editor/) and wanted to ask kindly if you are willing to put your file under the GPL v2 license? This would be needed in order to comply with the license of the original JOE project. No problem if you decline, though :)

**Comment by iarna** [comment]
Absolutely. In fact, dual licensed, GPL v2 and ISC:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by cmur2** [comment]
Wonderful, thanks!

**Comment by cmur2** [comment]
Might you extend your statement to "GPL v2 or any later version"? The original JOE project evaluated their licensing situation and would like to have the any-later-version option to be better prepared for future developments... I already updated this for myself in the README.

**Comment by iarna** [comment]
Sure. (Of course, ISC above, is permissive enough that I could have JUST licensed it under that and it'd be compatible with any version of the GPL.)

**Comment by cmur2** [comment]
Thanks. (Yea I guessed something like that but I'm not soo deep into license compatibility and didn't use ISC before...) Sorry for the trouble.

**Pull request merged**
