### PR TITLE
add backtick support for markdown (md.jsf)

### PR DESCRIPTION
**Pull request by utoddl**
This directly addresses issue #36 . Prior to this md.jsf did nothing for backticks.

### CODE REVIEW

**Comment by cmur2** [comment]
Ohh, on the first look I couldn't believe that this was not already implemented... ^^

I will have a look at that PR soon.

**Comment by utoddl** [comment]
The way I read the MD spec (which one? there are so many!), I'm looking for some number of backticks, something other than that same number of backticks, followed by that same number of backticks, where "that number" is limited to 31 by the syntax engine. But hey, if you've got more than 31 backticks, you've got other problems anyway.

**Comment by cmur2** [comment]
> The way I read the MD spec (which one? there are so many!)

That's one of the reasons why this started as joke - Markdown is just too floaty, under-specified and complex for JOE...

Anyways, thanks for that valuable contribution, nicely done! :+1:

> But hey, if you've got more than 31 backticks, you've got other problems anyway.

:smile:

**Comment by egmontkob** [comment]
Thanks a lot, guys! :)

**Pull request merged**
